services:
  daqreminder:
    build: .
    container_name: daqreminder
    volumes:
      - ./config.yml:/daqreminder/config.yml:ro
      - /etc/localtime:/etc/localtime
    environment:
      - LOG_LEVEL=info
