services:
  daqreminder:
    build: .
    container_name: daqreminder
    volumes:
      - ./config.yaml:/daqreminder/config.yaml:ro
      - /etc/localtime:/etc/localtime
    environment:
      - LOG_LEVEL=info
